# Use postgres/example user/password credentials
version: "3.1"

services:
  backend:
    image: "dmsc/duo-backend:${USER_OFFICE_BACKEND_TAG}"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://duouser:duopassword@db:5432/duo
      secret: qMyLZALzs229ybdQXNyzYRdju7X784TH
      tokenLife: 7d
      baseURL: localhost:3000
      SPARKPOST_TOKEN: dummytoken
      NODE_ENV: development
      USER_OFFICE_PDF_FACTORY_ENDPOINT: ${USER_OFFICE_PDF_FACTORY_ENDPOINT}
    labels:
      - "traefik.frontend.rule=PathPrefix:/api, /graphql, /downloads, /files, /download, /uploads"
      - "traefik.port=4000"
  duo-cron-job:
    image: dmsc/duo-cron-job
  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: duopassword
      POSTGRES_USER: duouser
      POSTGRES_DB: duo
    ports:
      - 5432:5432
    volumes:
      - "./${USER_OFFICE_BACKEND_DIR}/db_patches/:/docker-entrypoint-initdb.d/"
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - "./${USER_OFFICE_BACKEND_DIR}/rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config"
