// This file contains unique tokens for each dependency
export const Tokens = {
  RegisterAssetInExternalService: Symbol('RegisterAssetInExternalService'),
  AdminDataSource: Symbol('AdminDataSource'),
  CallDataSource: Symbol('CallDataSource'),
  EventLogsDataSource: Symbol('EventLogsDataSource'),
  FileDataSource: Symbol('FileDataSource'),
  InstrumentDataSource: Symbol('InstrumentDataSource'),
  ProposalDataSource: Symbol('ProposalDataSource'),
  ProposalSettingsDataSource: Symbol('ProposalSettingsDataSource'),
  QuestionaryDataSource: Symbol('QuestionaryDataSource'),
  ReviewDataSource: Symbol('ReviewDataSource'),
  SampleDataSource: Symbol('SampleDataSource'),
  SEPDataSource: Symbol('SEPDataSource'),
  ShipmentDataSource: Symbol('ShipmentDataSource'),
  SystemDataSource: Symbol('SystemDataSource'),
  TemplateDataSource: Symbol('TemplateDataSource'),
  UserDataSource: Symbol('UserDataSource'),
  UserAuthorization: Symbol('UserAuthorization'),
  QuestionaryAuthorization: Symbol('QuestionaryAuthorization'),
  SampleAuthorization: Symbol('SampleAuthorization'),
  ShipmentAuthorization: Symbol('ShipmentAuthorization'),
  QuestionaryAuthorizer: Symbol('QuestionaryAuthorizer'),
};
