name: Build, Test and Push

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop and master branches
on:
  pull_request:
    branches: [develop, master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: ${{ matrix.node-version }}-cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - run: npm ci --loglevel error --no-fund
      - run: npm run build
      - run: npm test
        env:
          NODE_ENV: test
          secret: ${{secrets.secret}}
          tokenLife: 7d
          SPARKPOST_TOKEN: wrong_token_for_test

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache app docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-layer-cache
          key: ${{ runner.os }}-buildx-${{ github.head_ref }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ github.head_ref }}-
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # For debugging capture the selected branch
      - name: Extracted branch
        run: echo "Extracted branch ${{ github.head_ref }}"

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: dmsc/duo-backend:${{ github.head_ref }}
          cache-from: type=local,src=/tmp/.buildx-layer-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-layer-cache
